version: '3.8'

services:
  db:
    image: ankane/pgvector:latest  # 带 pgvector 插件的 PostgreSQL
    container_name: postgres_pgvector
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: